apiVersion: casbin.org/v1alpha1
kind: CasbinPolicy
metadata:
  name: alice-data1-read
  namespace: default
spec:
  ptype: p
  rule:
    - alice
    - data1
    - read
---
apiVersion: casbin.org/v1alpha1
kind: CasbinPolicy
metadata:
  name: bob-data2-write
  namespace: default
spec:
  ptype: p
  rule:
    - bob
    - data2
    - write
---
apiVersion: casbin.org/v1alpha1
kind: CasbinPolicy
metadata:
  name: alice-admin-role
  namespace: default
spec:
  ptype: g
  rule:
    - alice
    - admin
